issues:
  exclude-rules:
    - path: /
      linters:
        - nlreturn
        - varnamelen
        - testpackage
        - gomnd
        - wsl
        - lll
        - gochecknoglobals
        - cyclop
        - paralleltest
        - exhaustivestruct
        - exhaustruct
        - wsl
        - dupl
        - errorlint
        - goerr113
        - forcetypeassert

linters:
  enable-all: true
