linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - interfacer
    - ireturn
    - loggercheck
    - maintidx
    - maligned
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - prealloc
    - promlinter
    - reassign
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - tagliatelle
    - tenv
    - testableexamples
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - varcheck
  fast: true
  auto-fix: false
run:
  timeout: 10m
  shell: bash
  command: |
    export GOLANGCI_LINT_SKIP="typecheck"
    golangci-lint run
