name: linter
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Golang Super Linter
        uses: docker://ghcr.io/github/super-linter:v4
        with:
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          args: >
            --config .github/workflows/linters/.golangci.yml
            --json
            --no-color
            --allow-missing-config
            --fail-on-warnings
      - name: Run Golang Super Linter
        run: |
          export GOLANGCI_LINT_SKIP="typecheck"
          golangci-lint run
